System:
  Default:
    Currency:
      Name: Dollar
      NamePlural: Dollars
      Minor: Coin
      MinorPlural: Coins
      MultiWorld: false
      #Show Money to pretty way
      LongMode: true
    Account:
      # Default account balance when created
      Holdings: 30.0

  Bank:
    Price: 50
    
  PayDay:
    Enabled: []

  Interest:
    # Enables the interest system
    Enabled: false
    # The interval of the system - in seconds
    # 60 => 1 minute
    Interval: 60
    # The currencys which shall get interest
    Currencys: [A,B]
    # Which currency shall gain what Percentage
    Percentage: [1,2]
    # The maximum amount of each currency, more a user
    # can't reach through interest
    EndMax: [1000, 1000]
    
  # Logs all monetary transactions passed through CraftConomy (NOT WORKING)
  Logging:
    Enabled: false

  Convert:
    Enabled: false
    Type: iconomy
    TableName: iConomy
    DatabaseType: mysql
    Address: localhost
    Port: 3306
    Username: root
    Password: test
    Database: iconomy
    
  Database:
    # Databases Supported:
    ##
    # mysql
    #  - These will attempt to connect to MySQL
    ##
    # sqlite
    #  - These will attempt to create & connect to SQLite
    Type: 'sqlite'

    # The table used for the accounts
    AccountTable: 'Account'
    BalanceTable: 'Balance'
    
    # The table used for the bank
    BankTable: 'Bank'
    BankBalanceTable: 'BankBalance'
    BankMemberTable: 'BankMember'
    
    # The table used for currency
    CurrencyTable: 'Currency'
    CurrencyExchangeTable: 'CurrencyExchange'    
    
    #Modify if using MySQL
    Address: 'localhost'
    Port: 3306
    Username: 'root'
    Password: ''
    Db: 'Craftconomy'
  Debug:
    fixName: false